--주석은 이렇게 사용
/*여러줄 주석
은 이렇게
*/

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS

--특정 컬럼만 확인하고 싶으면
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES;
--문자는 왼쪽, 날짜타입의 경우 왼쪽, 숫자타입의 경우 오른쪽 
SELECT FIRST_NAME, SALARY, COMMISSION_PCT, HIRE_DATE FROM EMPLOYEES;
--숫자컬럼은 * / + - 연산자
SELECT FIRST_NAME, SALARY, SALARY*12,SALARY+10000 FROM EMPLOYEES;

--별칭 AS
SELECT FIRST_NAME AS 이름, SALARY*12 연봉, SALARY 급여 FROM EMPLOYEES;

--문자열을 붙일 때 ||
SELECT FIRST_NAME ||' '|| LAST_NAME ||'님의 급여는 '||SALARY AS 급여 FROM EMPLOYEES;


--DISTINCT 키워드: 완전히 동일한 행에 대해서 중복제거
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES;

--ROWID:데이터가 저장되는 주소값
--ROWNUM:조회되는 순서에 일련번호를 붙임
SELECT FIRST_NAME,SALARY,ROWID, ROWNUM FROM EMPLOYEES;