--WHERE절
SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES WHERE JOB_ID='IT_PROG';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME='Steven';
SELECT * FROM EMPLOYEES WHERE SALARY>=10000;
SELECT * FROM EMPLOYEES WHERE SALARY<>10000;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE<='08/01/01';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE<='01/01/13';

--BETWEEN ~ AND 이상 이하
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 10000 AND 12000;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '05/01/01' AND '05/12/31';

--IN : 일치하는 값
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (50,60,70);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('ST_CLERK','IT_PROG');

--LIKE (%-무엇이든 들어올 수 있음, _-자리수)
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '03%';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%03';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%03%';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '_a%';

--IS NULL, IS NOT NULL
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

--AND,OR, -AND의 우선순위가 OR보다 빠름
SELECT * FROM EMPLOYEES WHERE JOB_ID='IT_PROG' OR SALARY>=5000;
SELECT * FROM EMPLOYEES WHERE (JOB_ID='IT_PROG' OR JOB_ID='FI_MGR') AND SALARY>=5000;

--NOT 키워드: 부정의 의미
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN (50,60);
SELECT * FROM EMPLOYEES WHERE HIRE_DATE NOT LIKE '03%';

--ORDER BY: SELECT절 마지막에 들어감
SELECT * FROM EMPLOYEES ORDER BY JOB_ID ASC;
SELECT * FROM EMPLOYEES ORDER BY JOB_ID; --안적어도 자동 오름차순
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;

--ORDER BY 절에는 별칭 사용가능, WHERE 절 X
SELECT FIRST_NAME AS 이름, SALARY FROM EMPLOYEES WHERE SALARY>=5000 ORDER BY 이름 DESC;


