--숫자 함수
--ROUND 반올림, TRUNC 절삭
SELECT ROUND(45.923),ROUND(45.923,2),ROUND(45.923,-1) FROM DUAL;
SELECT TRUNC(45.923),TRUNC(45.923,2),TRUNC(45.923,-1) FROM DUAL;
--ABS 절대값, CEIL 올림, FLOOR 내림, MOD 나머지
SELECT ABS(-4), CEIL(3.14),FLOOR(3.14) FROM DUAL;
SELECT 5/2 AS 몫, MOD(5,2) AS 나머지 FROM DUAL;


--날짜 함수
SELECT SYSDATE, SYSTIMESTAMP FROM DUAL;

--날짜는 연산이 가능하다
SELECT HIRE_DATE, HIRE_DATE+10, HIRE_DATE-10 FROM EMPLOYEES;  --날짜+ 숫자=날짜
SELECT HIRE_DATE, SYSDATE-HIRE_DATE FROM EMPLOYEES; --날짜-날짜=일수
SELECT (SYSDATE-HIRE_DATE)/365 FROM EMPLOYEES;  --입사일로부터 몇 년?
SELECT (SYSDATE-HIRE_DATE)/7 FROM EMPLOYEES; --입사일로부터 몇 주?

--ROUND, TRUNC
SELECT TRUNC(SYSDATE) FROM EMPLOYEES; --일 기준 절삭
SELECT TRUNC(SYSDATE, 'MONTH') FROM DUAL; --월 기준 절삭
SELECT TRUNC(SYSDATE, 'YEAR') FROM DUAL ; --년 기준 절삭

SELECT ROUND(SYSDATE) FROM EMPLOYEES; --일 기준 반올림
SELECT ROUND(SYSDATE, 'MONTH') FROM DUAL; --월 기준 반올림
SELECT ROUND(SYSDATE, 'YEAR') FROM DUAL ; --년 기준 반올림