--문제 1.
--EMPLOYEES, DEPARTMENTS 테이블을 엘리어스를 이용해서 조인해보세요.
--조건) 각각 INNER, LEFT, RIGHT 조인 해보세요.
--
SELECT *
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

SELECT *
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;
--문제 2.
--EMPLOYEES, DEPARTMENTS 테이블을 INNER JOIN하세요.
--조건)employee_id가 200인 사람의 이름, department_id를 출력하세요
--조건)이름 컬럼은 first_name과 last_name을 합쳐서 출력합니다
--
SELECT FIRST_NAME ||' '||LAST_NAME, E.DEPARTMENT_ID
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID AND EMPLOYEE_ID=200;
--문제 3.
--EMPLOYEES, JOBS테이블을 INNER JOIN하세요
--조건) 모든 사원의 이름과 직무아이디, 직무 타이틀을 출력하고, 이름 기준으로 오름차순 정렬
--HINT) 어떤 컬럼으로 서로 연결되 있는지 확인
--

SELECT FIRST_NAME,J.JOB_ID,J.JOB_TITLE
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID=J.JOB_ID
ORDER BY FIRST_NAME;
--문제 4.
--JOBS테이블과 JOB_HISTORY테이블을 조인하세요.
--조건) JOS_HISTORY테이블에 알맞는 부서명도 출력하세요.
--힌트) 조인 2번
--
SELECT * FROM DEPARTMENTS;
SELECT *
FROM JOBS J
INNER JOIN JOB_HISTORY H
ON J.JOB_ID=H.JOB_ID
INNER JOIN DEPARTMENTS D
ON H.DEPARTMENT_ID=D.DEPARTMENT_ID;
--문제 5.
--Steven King의 부서명을 출력하세요.
--
SELECT * FROM DEPARTMENTS;
SELECT DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE FIRST_NAME = 'Steven' AND LAST_NAME='King';
--문제 6.
--EMPLOYEES 테이블과 DEPARTMENTS 테이블을 Cartesian Product(Cross join)처리하세요
SELECT *
FROM EMPLOYEES E, DEPARTMENTS D;
---------------------------------------------------------------------------------------
--문제 7.
--EMPLOYEES 테이블과 DEPARTMENTS 테이블의 부서번호를 조인하고 SA_MAN 사원만의 사원번호, 이름, 
--급여, 부서명, 근무지를 출력하세요. (Alias를 사용)
--
SELECT * FROM LOCATIONS;
SELECT E.DEPARTMENT_ID,E.FIRST_NAME,E.SALARY, D.DEPARTMENT_NAME,L.CITY
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
ON D.LOCATION_ID=L.LOCATION_ID
WHERE JOB_ID='SA_MAN';
--문제 8.
--employees, jobs 테이블을 조인 지정하고 job_title이 'Stock Manager', 'Stock Clerk'인 직원 정보만
--출력하세요.
--
SELECT *
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID=J.JOB_ID
WHERE JOB_TITLE='Stock Manager' or JOB_TITLE='Stock Clerk';
--문제 9.
--departments 테이블에서 직원이 없는 부서를 찾아 출력하세요.
SELECT DEPARTMENT_NAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID AND E.EMPLOYEE_ID=null;
