--DML
--INSERT(삽입)
--2가지 방법
DESC DEPARTMENTS;

--INSERT INTO 테이블명(컬럼명) VALUES(값)
--1.컬럼명을 정확히 일치 시키면 컬럼명 생략이 가능함
INSERT INTO DEPARTMENTS VALUES(280,'개발자',NULL,1700);
--2.컬럼을 지정해서 넣는 경우
INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID)
VALUES(290,'디자이너',1700);

ROLLBACK; --모든 DML문은 트랜잭션이 반영됨
SELECT * FROM DEPARTMENTS;

--INSERT도 서브쿼리문장으로 넣을 수 있습니다
CREATE TABLE EMPS AS (SELECT * FROM EMPLOYEES WHERE 1=2);--테이블 구조 복사

SELECT * FROM EMPS;

DESC EMPS;
--EMPLOYEES 테이블에서 SA_MAN데이터를 통째로 EMPS에 INSERT하는 유형
INSERT INTO EMPS(LAST_NAME, EMAIL, HIRE_DATE,JOB_ID)
(SELECT LAST_NAME,EMAIL, HIRE_DATE, JOB_ID FROM EMPLOYEES WHERE JOB_ID='SA_MAN');
 
INSERT INTO EMPS(LAST_NAME, EMAIL, HIRE_DATE, JOB_ID)
VALUES((SELECT LAST_NAME FROM EMPLOYEES WHERE MANAGER_ID IS NULL),'TEST',SYSDATE,'TEST');
--------------------------------------------------------------------------------
--UPDATE
SELECT * FROM EMPS;

UPDATE EMPS
SET SALARY=1000;--전체 행 업데이트됨
UPDATE EMPS SET SALARY=SALARY*1.1,
                COMMISSION_PCT=0.5,
                MANAGER_ID=100
WHERE LAST_NAME='Russell'; --보통 WHERE절에는 key로 업데이트 진행함
--UPDATE구문도 서브쿼리절이 허용 됩니다
UPDATE EMPS
SET (MANAGER_ID, JOB_ID, DEPARTMENT_ID) = (SELECT MANAGER_ID,JOB_ID,DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID=103)
WHERE LAST_NAME='Russell';
--WHERE 절에도 서브쿼리가 가능함
UPDATE EMPS
SET SALARY=0
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE JOB_ID='IT_PROG');

--------------------------------------------------------------------------------

--DELETE
DELETE FROM EMPS
WHERE JOB_ID='IT_PROG';
--모든 행이 삭제가 되는 것은 아니다. 테이블이 연관관계를 가지고 있다면, 참조 무결성 제약에 위배되는 경우에 삭제되지 않습니다
DELETE FROM DEPARTMENTS WHERE DEPARTMENT_ID=90 --90번 데이터는 사용중이라 삭제 안됨
