--제약조건
--NOT NULL=NULL을 허용하지 않음
--UNIQUE KEY=중복 X, NULL허용
--PRIMARY KEY= 중복 X, NULL X, 테이블에서 한 개만 지정이 됨
--FOREIGN KEY=참조되는 테이블의 PK를 넣어놓은 키, 중복 O, NULL 허용
--CHECK=컬럼에 대한 데이터 제한

SELECT * FROM USER_CONSTRAINTS;


--1ST 열레벨 정의
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2) CONSTRAINT DEPTS_DEPT_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(30) CONSTRAINT DEPTS_DEPT_NAME_NN NOT NULL,
    DEPT_DATE DATE DEFAULT SYSDATE, --기본값 지정(제약X)
    DEPT_PHONE VARCHAR2(30) CONSTRAINT DEPTS_DEPT_PHONE_UK UNIQUE, 
    DEPT_GENDER CHAR(1) CONSTRAINT DEPTS_DEPT_GENDER_CK CHECK (DEPT_GENDER IN ('F','M')),
    LOCA_ID NUMBER(4) CONSTRAINT DEPTS_LOCA_ID_FK REFERENCES LOCATIONS(LOCATION_ID)--로케이션테이블(로케이션아이디)
);

INSERT INTO DEPTS (DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID)
VALUES (1,NULL, '010..','F',1700); --NOT NULL 위배
INSERT INTO DEPTS (DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID)
VALUES (1,'홍길동', '010..','X',1700); --CHECK 위배
INSERT INTO DEPTS (DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID)
VALUES (1,'홍길동', '010..','F',100); --참조제약 위배
INSERT INTO DEPTS (DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID)
VALUES (1,'홍길동', '010..','F',1700); --OK
INSERT INTO DEPTS (DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID)
VALUES (2,'홍길동', '010..','F',1700); --UNIQUE제약위배
----
DROP TABLE DEPTS;

--CONSTRAINT랑 제약조건이름 생략 가능 //BUT 쓰는게 나음
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2) PRIMARY KEY,
    DEPT_NAME VARCHAR2(30)   NOT NULL,
    DEPT_DATE DATE DEFAULT SYSDATE, --기본값 지정(제약X)
    DEPT_PHONE VARCHAR2(30) UNIQUE, 
    DEPT_GENDER CHAR(1) CHECK (DEPT_GENDER IN ('F','M')),
    LOCA_ID NUMBER(4)  REFERENCES LOCATIONS(LOCATION_ID)--로케이션테이블(로케이션아이디)
);
--2ND=테이블 레벨 정의
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR2(30) NOT NULL, --NOT NULL은 열레벨로 지정함
    DEPT_DATE DATE DEFAULT SYSDATE, --기본값 지정(제약X)
    DEPT_PHONE VARCHAR2(30), 
    DEPT_GENDER CHAR(1),
    LOCA_ID NUMBER(4),
    CONSTRAINT DEPTS_DEPT_NO_PK PRIMARY KEY (DEPT_NO, /* DEPT_NAME */),
    CONSTRAINT DEPTS_DEPT_PHONE_UK UNIQUE (DEPT_PHONE),
    CONSTRAINT DEPTS_DEPT_GENDER_CK CHECK (DEPT_GENDER IN ('F','M')),
    CONSTRAINT DEPTS_DEPT_LOCA_ID_FK FOREIGN KEY (LOCA_ID) REFERENCES LOCATIONS(LOCATION_ID)
);

--3rd (제약조건의 추가, 삭제)
CREATE TABLE DEPTS (
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR2(30) NOT NULL, --NOT NULL은 열레벨로 지정함
    DEPT_DATE DATE DEFAULT SYSDATE, --기본값 지정(제약X)
    DEPT_PHONE VARCHAR2(30), 
    DEPT_GENDER CHAR(1),
    LOCA_ID NUMBER(4)
);
--PK 추가
ALTER TABLE DEPTS ADD CONSTRAINT DEPTS_DEPT_NO_PK PRIMARY KEY (DEPT_NO);
--UK
ALTER TABLE DEPTS ADD CONSTRAINT DEPTS_DEPT_PHONE_UK UNIQUE (DEPT_PHONE);
--CHECK
ALTER TABLE DEPTS ADD CONSTRAINT DEPTS_DEPT_GENDER CHECK (DEPT_GENDER IN ('F','M'));
--FK 
ALTER TABLE DEPTS ADD CONSTRAINT DEPTS_LOCA_ID FOREIGN KEY (LOCA_ID) REFERENCES LOCATIONS(LOCATION_ID);
--NOT NULL은 MODIFY 문장으로 수정이 됩니다
ALTER TABLE DEPTS MODIFY DEPT_PHONE VARCHAR2(30) NOT NULL;

--제약조건 삭제
ALTER TABLE DEPTS DROP CONSTRAINT DEPTS_DEPT_GENDER;

DROP TABLE DEPTS;

--------------------------------------------------------------------------------
--문제1.
--
--다음과 같은 테이블을 생성하고 데이터를 insert해보세요.
--테이블 제약조건은 아래와 같습니다. 
--조건) M_NUM 은 숫자형 5자리, PRIMARY KEY 이름(mem_memnum_pk) 
--조건) M_NAME 는 가변문자형 20byte, 널값을 허용하지 않음
--조건) REG_DATE 는 날짜형, 널값을 허용하지 않음, UNIQUE KEY 이름:(mem_regdate_uk)
--조건) SALARY 숫자형 10자리, CHECK제약 (양수만 허용함)
--조건) LOCA 숫자형 4자리, FOREIGN KEY – 참조 locations테이블(location_id) 이름:(mem_loca_loc_locid_fk)
CREATE TABLE MEM (
    M_NUM NUMBER(5) CONSTRAINT MEM_MEMNUM_PK PRIMARY KEY,
    M_NAME VARCHAR(20) NOT NULL,
    REG_DATE DATE NOT NULL CONSTRAINT MEM_REGDATE_UK UNIQUE,
    SALARY NUMBER(10) CONSTRAINT MEM_SALARY_CK CHECK (SALARY>0),
    LOCA NUMBER(4) CONSTRAINT MEM_LOCA_LOC_LOCID_FK REFERENCES LOCATIONS(LOCATION_ID)
);

INSERT INTO MEM VALUES (1,'AAA','2018/07/01',5000,1800);
INSERT INTO MEM VALUES (2,'BBB','2018/07/02',3000,1900);
INSERT INTO MEM VALUES (3,'CCC','2018/07/03',3000,2000);
INSERT INTO MEM VALUES (4,'DDD',SYSDATE,2000,2000);



--문제2.
--도서테이블, 도서 대여 이력 테이블을 생성하려 합니다.
--도서 테이블은
--도서번호(문자) PK, 도서명(문자), 출판사(문자), 입고일(날짜)
--도서 대여 이력 테이블은
--대여번호(숫자) PK, 도서번호(문자) FK, 대여일(날짜), 반납일(날짜), 반납여부(Y/N)
--를 가집니다.
--적절한 테이블을 생성하고, 제약조건을 지정하세요.
CREATE TABLE BOOK (
    BOOK_NO VARCHAR(30) CONSTRAINT BOOK_BOOK_NO_PK PRIMARY KEY,
    BOOK_TITLE VARCHAR(30),
    COMPANY VARCHAR(30),
    ARRIVE_DATE DATE
);

CREATE TABLE BOOK_RESERV (
    RES_NO NUMBER(10) CONSTRAINT BOOK_RES_NO PRIMARY KEY,
    BOOK_NO VARCHAR(30) CONSTRAINT BOOK_BOOK_NO REFERENCES BOOK(BOOK_NO),
    BORROW_DATE DATE,
    RETURN_DATE DATE,
    RETURN_Y_N VARCHAR(1) CONSTRAINT BOOK_RESERV_RETURN_Y_N_CK CHECK (RETURN_Y_N IN ('Y','N'))
    
);
